function [ rho, i_a] = rhoIa( x_init, epsilon, beta_0, k, k_tau, r )
  x1 = x_init(1);
  x2 = x_init(2);
  x3 = x_init(3);
  x4 = x_init(3);
  
  run('initPendulum')
  
  %rho including g_b in bound
%   rho = (l*(M + m - m*cos(x1)^2)*(k2*(x3*x4*sin(x1) -...
%     (M*b_p_v*x3 + b_p_v*m*x3 + M*b_p_c*tanh(k_tan*x4) +...
%     b_p_c*m*tanh(k_tan*x4) - g*l*m^2*sin(x1) + ...
%     b_c_c*l*m*tanh(k_tan*x3)*cos(x1) + l^2*m^2*x4^2*cos(x1)*sin(x1) -...
%     M*g*l*m*sin(x1) + b_c_v*l*m*x4*cos(x1))/(l*m*(M + m - m*cos(x1)^2)) +...
%     (cos(x1)*(b_p_v*x3*cos(x1) + b_p_c*tanh(k_tan*x4)*cos(x1) + ...
%     b_c_v*l*x4 + b_c_c*l*tanh(k_tan*x3) + l^2*m*x4^2*sin(x1) -...
%     g*l*m*cos(x1)*sin(x1)))/(l*(M + m - m*cos(x1)^2))) + k1*x4 + k3*x3 -...
%     (M*b_p_v*x3 + b_p_v*m*x3 + M*b_p_c*tanh(k_tan*x4) +...
%     b_p_c*m*tanh(k_tan*x4) - g*l*m^2*sin(x1) +...
%     b_c_c*l*m*tanh(k_tan*x3)*cos(x1) + l^2*m^2*x4^2*cos(x1)*sin(x1) -...
%     M*g*l*m*sin(x1) + b_c_v*l*m*x4*cos(x1))/(l^2*m*(M + m -...
%     m*cos(x1)^2))))/cos(x1)  ;

  %rho not including g_b in bound
  rho = k2*(x3*x4*sin(x1) - (M*b_p_v*x3 + b_p_v*m*x3 + ...
        M*b_p_c*tanh(k_tan*x4) + b_p_c*m*tanh(k_tan*x4) - ...
        g*l*m^2*sin(x1) + b_c_c*l*m*tanh(k_tan*x3)*cos(x1) + ...
        l^2*m^2*x4^2*cos(x1)*sin(x1) - M*g*l*m*sin(x1) + ...
        b_c_v*l*m*x4*cos(x1))/(l*m*(M + m - m*cos(x1)^2)) +...
        (cos(x1)*(b_p_v*x3*cos(x1) + b_p_c*tanh(k_tan*x4)*cos(x1) +...
        b_c_v*l*x4 + b_c_c*l*tanh(k_tan*x3) + l^2*m*x4^2*sin(x1) -...
        g*l*m*cos(x1)*sin(x1)))/(l*(M + m - m*cos(x1)^2))) + k1*x4 +...
        k3*x3 - (M*b_p_v*x3 + b_p_v*m*x3 + M*b_p_c*tanh(k_tan*x4) +...
        b_p_c*m*tanh(k_tan*x4) - g*l*m^2*sin(x1) +...
        b_c_c*l*m*tanh(k_tan*x3)*cos(x1) +...
        l^2*m^2*x4^2*cos(x1)*sin(x1) - M*g*l*m*sin(x1) +...
        b_c_v*l*m*x4*cos(x1))/(l^2*m*(M + m - m*cos(x1)^2));
 
  %controller
  beta = rho + beta_0;
  
  s = x3 + k(1)*x2 + k(3)*x1 + k(2)*(0.3348*x3 - x4*cos(x1));
  u = -min( 1, max(-1, (1/epsilon)*s))*beta*(l*(M + m - m*cos(x1)^2))/cos(x1);
  
  i_a = u*r/k_tau;
end
