function [ eta_dot ] = simReducedOrderSystemOdeFun( t, eta, k, M, m, l, ...
                                                    g, k_tan,           ...
                                                    b_p_c, b_p_v,       ...
                                                    b_c_c, b_c_v        )
  xi = -k*eta;
  eta2 = eta(2);
  eta3 = eta(3);
  
  %reduced notation
  % eta_dot = [ -(eta2 - a*xi)/(c*cos(eta3))                       ;
  %              e*sin(eta3) - b_p_v*xi                            ...
  %            + b_p_c*tanh((k_tan*(eta2 - a*xi))/(c*cos(eta3)))   ...
  %            + c*xi*sin(eta3)                                    ;
  %              xi                                               ];

  eta_dot = [ -(eta2 - l*xi)/cos(eta3)                                  ;
               (b_p_c*tanh((k_tan*(eta2 - l*xi))/cos(eta3))*cos(eta3) - ...
               b_p_v*xi*cos(eta3) + l^2*m*xi^2*sin(eta3) +              ...
               (g*l*m*sin(2*eta3))/2 -                                  ...
               eta2*l*m*xi*sin(eta3))/(l*m*cos(eta3))                   ;
               xi                                                      ];
end