function [ eta_dot ] = simReducedOrderSystemOdeFun( t, eta, k, a, c, d, ...
                                                    e, k_tan,           ...
                                                    b_p_c, b_p_v,       ...
                                                    b_c_c, b_c_v        )
  xi = -k*eta;
  eta2 = eta(2);
  eta3 = eta(3);
  
  eta_dot = [ -(eta2 - a*xi)/(c*cos(eta3))                       ;
               e*sin(eta3) - b_p_v*xi                            ...
             + b_p_c*tanh((k_tan*(eta2 - a*xi))/(c*cos(eta3)))   ...
             + c*xi*sin(eta3)                                    ;
               xi                                               ];
end